# Generated by Django 5.2.8 on 2025-12-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('premium', 'Premium'), ('minimum', 'Minimum')], default='regular', max_length=20),
        ),
    ]
