# Generated by Django 5.2.8 on 2025-12-10 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_api', '0003_cms_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteConduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_type', models.CharField(choices=[('quality', 'Quality'), ('speed', 'Speed'), ('trust', 'Trust'), ('support', 'Support'), ('innovation', 'Innovation'), ('value', 'Value'), ('other', 'Other')], default='other', max_length=50)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='conducts/')),
                ('icon_css_class', models.CharField(blank=True, help_text='e.g., fas fa-check', max_length=100, null=True)),
                ('highlight_color', models.CharField(default='#007bff', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_conducts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'website_conducts',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_number', models.CharField(max_length=100, unique=True)),
                ('enquiry_type', models.CharField(choices=[('product', 'Product Inquiry'), ('service', 'Service Inquiry'), ('partnership', 'Partnership'), ('support', 'Support'), ('other', 'Other')], default='other', max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted to Lead'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL)),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_enquiries', to=settings.AUTH_USER_MODEL)),
                ('interested_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_api.product')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_enquiries', to='erp_api.lead')),
            ],
            options={
                'db_table': 'website_enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteHeroHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_position', models.CharField(choices=[('home', 'Homepage'), ('products', 'Products Page'), ('services', 'Services Page'), ('about', 'About Page'), ('contact', 'Contact Page'), ('custom', 'Custom Page')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hero_image', models.ImageField(upload_to='hero_headers/')),
                ('cta_button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('cta_button_url', models.CharField(blank=True, max_length=500, null=True)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_headers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'website_hero_headers',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteProductDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('website_description', models.TextField()),
                ('website_image', models.ImageField(blank=True, null=True, upload_to='website_products/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_displayed', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('show_price', models.BooleanField(default=True)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('call_to_action', models.CharField(default='Get a Quote', max_length=100)),
                ('page_sections', models.CharField(blank=True, help_text='Comma-separated page sections where this product should appear (e.g., homepage, products_page)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_product_displays', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_displays', to='erp_api.product')),
            ],
            options={
                'db_table': 'website_product_displays',
                'ordering': ['-is_featured', 'display_order'],
            },
        ),
    ]
