# Generated by Django 5.2.8 on 2025-12-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_api', '0007_websiteorder_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteorder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='websiteorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='websiteorder',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
