# Generated by Django 5.2.8 on 2025-12-10 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_api', '0008_websiteorder_customer_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageFooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_title', models.CharField(max_length=255)),
                ('column_type', models.CharField(choices=[('about', 'About Us'), ('menu', 'Menu Links'), ('account', 'Account Links'), ('info', 'Information Links'), ('contact', 'Contact Info')], max_length=50)),
                ('content', models.TextField(blank=True, help_text='For contact, use JSON format', null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Footer Sections',
                'db_table': 'homepage_footer_sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_type', models.CharField(choices=[('hammer', 'Artisanal Craftsmanship'), ('leaf', 'Sustainability'), ('palette', 'Customization'), ('shield', 'Durability'), ('truck', 'Fast Shipping'), ('heart', 'Quality'), ('star', 'Excellence'), ('check', 'Verified')], default='check', max_length=50)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='homepage/features/')),
                ('background_color', models.CharField(default='#f9f8f6', max_length=7)),
                ('text_color', models.CharField(default='#5a5a5a', max_length=7)),
                ('accent_color', models.CharField(default='#d4a574', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Features',
                'db_table': 'homepage_features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageFooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.CharField(max_length=255)),
                ('link_url', models.CharField(max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(limit_choices_to={'column_type__in': ['menu', 'account', 'info']}, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='erp_api.homepagefootersection')),
            ],
            options={
                'db_table': 'homepage_footer_links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Where Quality Meets Style', max_length=255)),
                ('subheading', models.TextField(default='Discover our curated collection of premium furniture and home decor for every room in your home')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='homepage/hero/')),
                ('background_color', models.CharField(default='#1a1a1a', help_text='Hex color code (e.g., #1a1a1a)', max_length=7)),
                ('cta_button_text', models.CharField(default='Shop Now', max_length=100)),
                ('cta_button_url', models.CharField(default='/products/', max_length=500)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_section_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
                'db_table': 'homepage_hero_section',
            },
        ),
        migrations.CreateModel(
            name='HomepageNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('icon_class', models.CharField(blank=True, help_text="FontAwesome icon class (e.g., 'fas fa-home')", max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_dropdown', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='erp_api.homepagenavigation')),
            ],
            options={
                'verbose_name_plural': 'Navigation Items',
                'db_table': 'homepage_navigation',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('why_us', 'Why Choose Us'), ('details', 'Details Are Important'), ('stories', 'Stories & Blog'), ('instagram', 'Instagram Follow'), ('testimonials', 'Testimonials'), ('cta', 'Call to Action'), ('custom', 'Custom Section')], max_length=50, unique=True)),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='homepage/sections/')),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#2e2e2e', max_length=7)),
                ('accent_color', models.CharField(default='#d4a574', max_length=7)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sections',
                'db_table': 'homepage_sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageInstagramSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_handle', models.CharField(default='@CozyCorner', max_length=100)),
                ('instagram_url', models.URLField(default='https://instagram.com/')),
                ('grid_items_count', models.IntegerField(default=6)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(limit_choices_to={'section_type': 'instagram'}, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_config', to='erp_api.homepagesection')),
            ],
            options={
                'verbose_name': 'Instagram Section',
                'verbose_name_plural': 'Instagram Section',
                'db_table': 'homepage_instagram_section',
            },
        ),
        migrations.CreateModel(
            name='HomepageDetailCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_type', models.CharField(choices=[('truck', 'Fast Shipping'), ('undo', 'Easy Returns'), ('headset', 'Expert Support'), ('check', 'Quality'), ('heart', 'Care'), ('star', 'Premium')], default='check', max_length=50)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='homepage/details/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(limit_choices_to={'section_type': 'details'}, on_delete=django.db.models.deletion.CASCADE, related_name='detail_cards', to='erp_api.homepagesection')),
            ],
            options={
                'verbose_name_plural': 'Detail Cards',
                'db_table': 'homepage_detail_cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='CozyCorner - Premium Furniture & Home Decor', max_length=255)),
                ('meta_description', models.TextField(default='Discover our curated collection of premium furniture and home decor', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='homepage/seo/')),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Homepage SEO',
                'verbose_name_plural': 'Homepage SEO',
                'db_table': 'homepage_seo',
            },
        ),
        migrations.CreateModel(
            name='HomepageSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('pinterest', 'Pinterest'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube')], max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='FontAwesome icon class', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Social Links',
                'db_table': 'homepage_social_links',
                'ordering': ['order'],
                'unique_together': {('platform',)},
            },
        ),
        migrations.CreateModel(
            name='HomepageStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('featured_image', models.ImageField(upload_to='homepage/stories/')),
                ('story_date', models.DateField()),
                ('icon_type', models.CharField(default='home', help_text="FontAwesome icon name (e.g., 'home', 'sofa', 'utensils')", max_length=50)),
                ('read_more_url', models.CharField(default='#', max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(limit_choices_to={'section_type': 'stories'}, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='erp_api.homepagesection')),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'db_table': 'homepage_stories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('author_title', models.CharField(default='Verified Purchase', max_length=255)),
                ('rating', models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('testimonial_text', models.TextField()),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='homepage/testimonials/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(limit_choices_to={'section_type': 'testimonials'}, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='erp_api.homepagesection')),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
                'db_table': 'homepage_testimonials',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageWhyUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(limit_choices_to={'section_type': 'why_us'}, on_delete=django.db.models.deletion.CASCADE, related_name='why_us_items', to='erp_api.homepagesection')),
            ],
            options={
                'verbose_name': 'Why Us Item',
                'verbose_name_plural': 'Why Us Items',
                'db_table': 'homepage_why_us_items',
                'ordering': ['order'],
            },
        ),
    ]
