# Generated by Django 6.0 on 2025-12-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_api', '0009_homepagefootersection_homepagefeature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Welcome to CozyCorner', max_length=200)),
                ('subheading', models.CharField(default='Make your space beautiful and comfortable', max_length=200)),
                ('description', models.TextField(default='Discover our curated selection of cozy home products, designed to bring warmth and style to every corner.')),
                ('hero_image', models.URLField(default='https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=800&q=80')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'site_info',
            },
        ),
    ]
