# Generated by Django 5.2.8 on 2025-12-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_api', '0010_siteinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='heading',
            field=models.CharField(default='Welcome to CozyCorner', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='siteinfo/'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='subheading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
