# Generated by Django - Manual SQL migration
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('erp_api', '0011_remove_siteinfo_description_siteinfo_about_text_and_more'),
    ]

    operations = [
        # Manually add created_at column if it doesn't exist
        migrations.RunSQL(
            sql="ALTER TABLE site_info ADD COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP;",
            reverse_sql="ALTER TABLE site_info DROP COLUMN `created_at`;",
            state_operations=[]
        ),
    ]
