# Generated by Django 5.2.8 on 2025-12-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_api', '0012_add_siteinfo_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('shipping', 'Shipping'), ('returns', 'Returns'), ('payment', 'Payment'), ('products', 'Products')], default='shipping', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'website_faq',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='website/gallery/')),
                ('image_url', models.URLField(blank=True, help_text='Base64 or URL for image', null=True)),
                ('category', models.CharField(choices=[('rooms', 'Living Rooms'), ('bedrooms', 'Bedrooms'), ('kitchens', 'Kitchens'), ('outdoor', 'Outdoor')], default='rooms', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'website_gallery',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('cta_text', models.CharField(blank=True, default='Explore Products', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/hero/')),
                ('image_url', models.URLField(blank=True, help_text='Base64 or URL for image', null=True)),
                ('background_color', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'website_hero',
            },
        ),
        migrations.CreateModel(
            name='WebsiteNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Subscribe to Our Newsletter', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('placeholder', models.CharField(default='Enter your email', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'website_newsletter',
            },
        ),
        migrations.CreateModel(
            name='WebsitePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='website/partners/')),
                ('logo_url', models.URLField(blank=True, help_text='Base64 or URL for logo', null=True)),
                ('link', models.URLField(blank=True, help_text='Partner website link', null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'website_partners',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/stories/')),
                ('image_url', models.URLField(blank=True, help_text='Base64 or URL for image', null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'website_stories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/testimonials/')),
                ('image_url', models.URLField(blank=True, help_text='Base64 or URL for image', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'website_testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='about_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
