# Generated by Django 5.2.8 on 2025-12-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_api', '0013_websitefaq_websitegallery_websiteherosection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='description',
        ),
        migrations.AlterField(
            model_name='websitegallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='website/gallery/'),
        ),
    ]
