# Generated by Django 5.2.8 on 2025-12-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_api', '0014_gallery_image_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitepartner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='website/partners/'),
        ),
    ]
