# Generated by Django 5.2.8 on 2025-12-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_api', '0015_partner_logo_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteherosection',
            name='hero_box_text',
            field=models.TextField(blank=True, help_text='Text for the left side white box'),
        ),
        migrations.AddField(
            model_name='websiteherosection',
            name='hero_box_title',
            field=models.CharField(blank=True, help_text='Title for the left side box', max_length=255),
        ),
    ]
