# Generated by Django 6.0 on 2025-12-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_api', '0016_websiteherosection_hero_box_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteCollectionsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='OUR LATEST COLLECTIONS', max_length=255)),
                ('description', models.TextField(blank=True, default='Discover our curated selection of premium furniture pieces')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'website_collections',
            },
        ),
    ]
