# Generated by Django 6.0 on 2025-12-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_api', '0017_websitecollectionssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteQualitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='Where Quality Meets Style', max_length=255)),
                ('description', models.TextField(blank=True, default='Every piece in our collection is carefully selected to ensure it meets our high standards for quality, design, and functionality.')),
                ('image_url', models.URLField(blank=True, help_text='Section image URL', null=True)),
                ('cta_text', models.CharField(blank=True, default='Explore More', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'website_quality',
            },
        ),
    ]
