# Generated by Django 5.2.8 on 2025-12-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_api', '0018_websitequalitysection'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteFurnitureDetailsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='Why Our Furniture Is Something More?', max_length=255)),
                ('subheading', models.CharField(blank=True, default='Details Are Important', max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=list, help_text='List of detail items with checkmarks')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'website_furniture_details',
            },
        ),
    ]
