# Generated by Django 5.2.8 on 2025-12-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_api', '0019_websitefurnituredetailssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteTestimonialsSectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='What Our Customers Say', max_length=255)),
                ('description', models.TextField(blank=True, default='Hear from our satisfied customers about their experiences')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'website_testimonials_section',
            },
        ),
    ]
