# Generated by Django 5.2.8 on 2025-12-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_api', '0020_websitetestimonialssectionsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteStoriesSectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='Our Latest Collections', max_length=255)),
                ('description', models.TextField(blank=True, default='Discover our curated selection of premium furniture pieces')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'website_stories_section',
            },
        ),
    ]
